### ISSUE TITLE
macOS Support

### ISSUE THREAD

**Issue by AndroidNils** [brianegan/chewie#315]
If this PR https://github.com/flutter/plugins/pull/2437 is merged, then will `chewie` also work on macOS 🥳

As long as the PR is not merged, you can use this code:

```
dependency_overrides:
  video_player:
    git:
      url: https://github.com/cbenhagen/plugins.git
      path: packages/video_player/video_player
      ref: video_player_macos
```

![image](https://user-images.githubusercontent.com/24459435/82808209-d0dbdf00-9e89-11ea-935b-4d6923a43a7c.png)
